config/routes.rb
Rails.application.routes.draw do
  root to: 'equipments#index'

  resources :equipments do
    collection do
      get 'list'
      get 'search'
    end
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :equipment

  validates :user_id, presence: true
  validates :equipment_id, presence: true
  has_many :reviews, dependent: :destroy
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  include AlgoliaSearch

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  def photo_helper
    remote_photo_url ? photo : ''
  end


  algoliasearch do
    attribute :name, :category
    searchableAttributes ['name', 'category']
    customRanking ['desc(likes_count)']
  end

  def rating
    rating = 0
    count = 0
    self.bookings.each do |b|
      b.reviews.each do |r|
        rating += r.rating
        count += 1
      end
    end
    rating = rating / count unless count == 0
    return rating
  end

  def marker
    {
      lat: user.latitude,
      lng: user.longitude#,
      # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
    }
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :description, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :equipments, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: [:search, :index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index], unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  protected

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    @bookings = policy_scope(Booking).where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])
    @equipment = Equipment.find_by(id: params[:id])
    @review = Review.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.equipment = Equipment.find(params[:equipment_id])
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

    def destroy
      @booking = Booking.find(params[:id])
      authorize @booking
      @booking.destroy
      redirect_to bookings_path
    end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :equipment_id, :start_date, :end_date)
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :set_equipment, only: [:show, :destroy]

  def index
    if params[:query].present?
      @equipments = Equipment.search(params[:query])
    else
      @equipments = Equipment.all
    end
    @markers = @equipments.map(&:marker)
  end

  def show
    authorize @equipment
    @booking = Booking.new
  end

  def new
    @equipment = Equipment.new
    authorize @equipment
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.user = current_user
    authorize @equipment
    if @equipment.save
      redirect_to @equipment
    else
      render :new
    end
  end

  def search
    @equipments = policy_scope(Equipment).order(created_at: :desc).search(params[:query])
    @markers = @equipments.map(&:marker)

    respond_to do |format|
      format.html
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def list
    @equipments = policy_scope(Equipment).order(created_at: :desc).where(user_id: current_user.id)
    authorize @equipments
  end

  def edit
    @equipment = Equipment.find_by(id: params[:id])
  end

  def update
    @equipment = Equipment.find_by(id: params[:id])
    @equipment.update(equipment_params)
    redirect_to equipment_path
  end

  def destroy
    authorize @equipment
    @equipment.destroy
    redirect_to list_equipments_path
  end

  protected

  def skip_pundit?
    controller_path == "equipments"
  end

  private



  def set_equipment
    @equipment = Equipment.find(params[:id])
  end

  def equipment_params
    params.require(:equipment).permit(:name, :description, :price, :category, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_booking

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = set_booking
    @booking = set_booking
    authorize @review
    if @review.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Booking was successfully destroyed.' }
    end
  end

  private

  def set_booking
    Booking.find_by(id: params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:booking_id, :description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container_form">
  <h3 class="booking-title">Book Now</h3>

  <%= simple_form_for [@equipment, @booking] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="text-center">My Bookings</h1>
  <div class="row extra-space">
    <% @bookings.each do |booking| %>
    <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path(booking.equipment.photo) %>);">
        <div class="card-category"><%= booking.equipment.name %>
          <br>
          <% rating = 0 %>
          <% count = 0 %>
          <% booking.reviews.each do |r| %>
          <% rating += r.rating %>
          <% count += 1 %>
          <% end %>
          <% rating = rating / count unless count == 0 %>
          <%= '*' * rating %>
        </div>
        <div class="card-category">
        </div>
        <div class="card-description">
          <h2>Full price: €<%= booking.equipment.price * (booking.end_date.day - booking.start_date.day) %> (€<%= booking.equipment.price %>/day)</h2>
          <p><strong><%= booking.start_date.strftime("%d-%m-%Y") %> | <%= booking.end_date.strftime("%d-%m-%Y") %></strong></p>
        </div>
        <!-- <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
        <%= link_to booking.user_id, equipment_booking_path(booking.equipment, booking), class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="bottom_container">
  <h2 class="manage">Manage Your Bookings</h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="content_container">
          <img class="icon1" src="https://res.cloudinary.com/djjncf5oe/image/upload/v1534519222/jfgn9gmzueihhyog3yv4.png" alt="">
          <h3 class="icon_text">View details</h3>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="content_container">
          <img class="icon1" src="https://res.cloudinary.com/djjncf5oe/image/upload/v1534519478/bqpkewlgf1fb7pzoym7f.png" alt="">
          <h3 class="icon_text">Add review</h3>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="content_container">
          <img class="icon1" src="https://res.cloudinary.com/djjncf5oe/image/upload/v1534519487/btqv1okj5vte0kukoiqh.png" alt="">
          <h3 class="icon_text">Cancel booking</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
    <h1 class="booking_details text-center"><%= @booking.equipment.name %> - Booking</h1>
  <div class="row">

    <div class="col-xs-12 col-md-6" id="firstcol">
      <img src="<%= cl_image_path @booking.equipment.photo, crop: :fill %>" alt="" width="400px" height="200" class="img-show" style="background-size: cover;">
      <br>
      <br>
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x200&sensor=false&maptype=roadmap&markers=color:red|#{@booking.equipment.user.address}&key=#{ENV['GOOGLE_API_BROWSER_KEY']}&style=feature:administrative|element:labels.text.fill|color:0x444444&style=feature:landscape|element:all|color:0xf2f2f2&style=feature:landscape.man_made|element:geometry.fill|color:0xff0000|visibility:off&style=feature:landscape.natural.landcover|element:geometry.fill|color:0xff0000|visibility:off&style=feature:poi|element:all|visibility:off&style=feature:road|element:all|saturation:-100|lightness:45&style=feature:road.highway|element:all|visibility:simplified&style=feature:road.highway|element:geometry.fill|color:0xea9f1f|saturation:52|lightness:0&style=feature:road.arterial|element:labels.icon|visibility:off&style=feature:transit|element:all|visibility:off&style=feature:water|element:all|color:#469AE0|visibility:on&style=feature:water|element:geometry.fill|color:#469AE0", class: "static-map img-show" %>
      <br><br>
      <div class="link" style="margin-left: 9px;">
      <%= link_to "Cancel this booking", booking_path,
      method: :delete,
      data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>
    </div>
    </div>
    <br>
    <br>
    <div class="col-xs-12 col-md-6" id="secondcol">
      <div class="details_content">
        <p><strong>Period: </strong><%= @booking.start_date.strftime("%d-%m-%Y") %> - <%= @booking.end_date.strftime("%d-%m-%Y") %></p>
        <p><strong>Price per day: </strong>€<%= @booking.equipment.price %></p>
        <p><strong>Total price is: </strong>€<%= @booking.equipment.price * (@booking.end_date.day - @booking.start_date.day) %></p>
        <br>
        <div>
          <%= render '/reviews/review_form', booking: [@booking, @review] %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/equipments/_edit_form.html.erb
<%= simple_form_for(@equipment, url: equipment_path, method: :patch) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<% sports = [
"kite surfing",
"wake boarding",
"snow boarding",
"skiing",
"surfing",
"football",
"baseball",
"golf",
"water polo",
"real polo",
"paragliding",
"luging",
"horseing around",
"cricket",
"croquet",
"conkers",
"tennis",
"ping pong",
"badminton",
"basketball",
"hockey"
] %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "Kitesurf" %>
    <%= f.input :description, placeholder: "Most badass Kitesurf ever"  %>
    <%= f.input :price, placeholder: "150"  %>
    <%= f.label :category %>
    <%= f.select :category, sports %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/equipments/_form.html.erb
<%= simple_form_for(@equipment, url: equipments_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<% sports = [
"kite surfing",
"wake boarding",
"snow boarding",
"skiing",
"surfing",
"football",
"baseball",
"golf",
"water polo",
"real polo",
"paragliding",
"luging",
"horseing around",
"cricket",
"croquet",
"conkers",
"tennis",
"ping pong",
"badminton",
"basketball",
"hockey"
] %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "Kitesurf" %>
    <%= f.input :description, placeholder: "Most badass Kitesurf ever"  %>
    <%= f.input :price, placeholder: "150"  %>
    <%= f.label :category %>
    <%= f.select :category, sports %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/equipments/_search.html.erb
<%= render "search_results", equipments: @equipments %>

app/views/equipments/_search_results.html.erb
<%= render 'shared/card', equipment: @equipment %>

app/views/equipments/edit.html.erb
<h1>Edit Equipment Listing</h1>

<%= render 'edit_form', equipment: @equipment %>
<br>
<%= link_to 'Back', @equipment %>

app/views/equipments/index.html.erb
<%= render 'shared/banner' %>
<%= render 'shared/card', @equipment %>

<div
  id="map"
  style="width: 100%;
  height: 300px;"
  data-markers="<%= @markers.to_json %>"
></div>

app/views/equipments/list.html.erb
<div class="container">
  <h1 class="text-center">My equipment</h1>
  <%= render 'shared/card', @equipment %>
</div>
<div class="bottom_container">
  <h2 class="manage">Manage Your Equipment</h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="content_container">
          <img class="icon1" src="https://res.cloudinary.com/djjncf5oe/image/upload/v1534519222/jfgn9gmzueihhyog3yv4.png" alt="">
          <h3 class="icon_text">View equipment</h3>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="content_container">
          <img class="icon1" src="https://res.cloudinary.com/djjncf5oe/image/upload/v1534520031/wmur28ixmivjfvbbcxw0.png" alt="">
          <h3 class="icon_text">Change details</h3>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="content_container">
          <img class="icon1" src="https://res.cloudinary.com/djjncf5oe/image/upload/v1534520109/o0lsejzktfnmcm9gqfe9.png" alt="">
          <h3 class="icon_text">Add photos</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/equipments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3 class="new_equipment">New Equipment Listing</h3>
      <%= render 'form', equipment: @equipment %>
      <br>
      <%= link_to 'Back', root_path %>
    </div>
    <div class="col-md-6">
      <img class="blue" src="https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/itCjTBE/light-blue-tech-geometric-polygonal-motion-background-video-corporate-animation-hd-1920x1080_nde0ffkig__F0000.png" alt="">
    </div>
  </div>
</div>

app/views/equipments/search.html.erb
<%= render 'shared/banner' %>
<%= render "search_results", equipments: @equipments %>

app/views/equipments/search.js.erb
function displaySearch(searchHTML) {
  document.querySelector(".title h1").innerHTML = "Top Results"
  cards = document.querySelector(".fix-margin")
  cards.innerHTML = ""
  cards.innerHTML = searchHTML

  document.map.removeMarkers()
  document.map.addMarkers(<%= @markers.to_json.html_safe %>)
}

displaySearch('<%= j render "search", equipments: @equipments %>')
window.smoothscroll(document.querySelector('.title'))

app/views/equipments/show.html.erb
<div class="container">
  <h1 class="booking_details text-center"><%= @equipment.name.capitalize %> - by <%= @equipment.user.first_name %></h1>
  <div class="row">
    <div class="col-xs-12 col-md-6" id="firstcol">
      <img src="<%= cl_image_path @equipment.photo, crop: :fill %>" alt="" width="400px" height="200" class="img-show">
      <br>
      <br>
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x200&sensor=false&maptype=roadmap&markers=color:red|#{@equipment.user.address}&key=#{ENV['GOOGLE_API_BROWSER_KEY']}&style=feature:administrative|element:labels.text.fill|color:0x444444&style=feature:landscape|element:all|color:0xf2f2f2&style=feature:landscape.man_made|element:geometry.fill|color:0xff0000|visibility:off&style=feature:landscape.natural.landcover|element:geometry.fill|color:0xff0000|visibility:off&style=feature:poi|element:all|visibility:off&style=feature:road|element:all|saturation:-100|lightness:45&style=feature:road.highway|element:all|visibility:simplified&style=feature:road.highway|element:geometry.fill|color:0xea9f1f|saturation:52|lightness:0&style=feature:road.arterial|element:labels.icon|visibility:off&style=feature:transit|element:all|visibility:off&style=feature:water|element:all|color:#469AE0|visibility:on&style=feature:water|element:geometry.fill|color:#469AE0", class: "static-map" %>
      <br>
      <br>
      <% if current_user.nil? %>
      <% elsif @equipment.user_id == current_user.id %>
        <div class="link">
          <%= link_to "Edit this equipment", edit_equipment_path, method: :get, class:"btn btn-warning" %>
        </div>
      <% end %>
      <br>
      <% if current_user.nil? %>
      <% elsif @equipment.user_id == current_user.id %>
        <div class="link">
          <%= link_to "Delete this equipment", equipment_path, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-6 details_content" id="secondcol">
      <br>
      <p><%= @equipment.description %></p>
      <p><strong>€<%= @equipment.price %> per day</strong></p>
      <%= render 'bookings/form', equipment: [@equipment, @booking] unless current_user.nil? || @equipment.user_id == current_user.id %>
      <% unless @equipment.reviews.empty? %>
      <ul class="list-group container_form">
        <% @equipment.reviews.each do |review| %>
          <li class="list-group-item details_content">
            <p><strong><%= review.description %></strong></p>
            <p>Rating: <%= '*' * review.rating %></p>
            <p>- <%= review.booking.user.first_name %></p>
          </li>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>EQUIP ME!</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <div class="content">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_pack_tag 'map' %>
  <%= javascript_pack_tag 'search' %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_review_form.html.erb
<div class="container_form">
<h3 class="booking-title">Add a Review</h3>

<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" style="width: 90%; font-family: roboto; color: #469AE0;">
    <%= f.input :description, as: :text, html5: true %>
    <%= f.input :rating, as: :integer, html5: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= cl_image_path 'koiqg9hk3xyk003ex6ej' %>);">
  <div class="banner-content">
    <h1>Equip your trip</h1>
    <p>Fun, only a few clicks away</p>
    <%= render "./shared/search_form" %>
    <!-- <a class="btn btn-primary btn-lg">Future search bar</a> -->
  </div>
</div>
<div class="title">
 <h1>Top Picks</h1>
</div>

app/views/shared/_card.html.erb
<div class="row fix-margin">
  <% @equipments.each do |equipment| %>
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path(equipment.photo) %>);">
      <div class="card-category"><%= equipment.category %></div>
      <div class="card-description">
        <h2><%= equipment.name %> | €<%= equipment.price %>/day</h2>
        <p><%= equipment.description.truncate(45) %></p>
        <p><strong><%= '*' * equipment.rating %></strong></p>
      </div>
      <!-- <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
      <%= link_to "", equipment, class: "card-link" %>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fas fa-football-ball"></i></a>
    <a href="#"><i class="fas fa-futbol"></i></a>
    <a href="#"><i class="fas fa-basketball-ball"></i></a>
    <a href="#"><i class="fas fa-bowling-ball"></i></a>
    <a href="#"><i class="fas fa-volleyball-ball"></i></a>
  </div>
  <div class="footer-copyright">
    This footer was made with <i class="fas fa-beer"></i>  at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo">
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag "ka9hi9ilmk2vsnyivns0", height: 50 %>
  <% end %>
  </div>
  <div class="logo_text">
    <h2>EquipMe</h2>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Equipment", list_equipments_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to 'Add new equipment', new_equipment_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "logged in as: #{current_user.first_name}", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "placeholder_avatar-400x400.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <!-- <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li> -->
            <!-- <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "My Equipment", list_equipments_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %><% end %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_review.html.erb
<ul>
  <% @equipment.reviews.each do |review| %>
  <li>
    <h3><%= review.description %></h3>
    <p><%= '*' * review.rating %></p>
    <p>- <%= @equipment.user.first_name %></p>
  </li>
  <% end %>
</ul>

app/views/shared/_search_form.html.erb
<%= form_tag search_equipments_path, remote: true, method: :get do %>
      <div class="form-inline">
        <%= text_field_tag :query,
        params[:query],
        class: "form-control input-md",
        style: "font-weight: lighter; font-family: Roboto;",
        placeholder: "Find equipment"
      %>
      <%= submit_tag("Search", class: "btn btn-md btn-primary", style: "font-family: Roboto;", id: "btn") %>
      </div>
     <% end %>